# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    network_mode: host
    volumes:
      - $HOME/mongo:/data/db/
   

  spring: 
    image: movie-image
    build: Movie/
    restart: always
    network_mode: host
    hostname: localhost
    container_name: movie-demo
    depends_on:
           - mongo
    ports: 
          - 8080:8080

